### ISSUE TITLE
Quantum Hangar server crash XML Serialization

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangar#15]
Not really sure what led to it; here's logs a few minutes prior and then the biggest stack trace I've seen

```11:45:17.5881 [INFO]   Torch.Commands.CommandManager: Player Doc Schoepp ran command '!hangar list'
11:45:50.1029 [INFO]   RexFix.Patches.ClusterReorderPatch: Clusters reordering. Prevented 22985 reorder calls.
11:46:37.6540 [INFO]   CrunchUtilities.CrunchUtilitiesPlugin: Updating names
11:46:52.6520 [INFO]   ServerGatePlugin.BoundrySystem.BoundaryThread: Transport Grid Recieved!
11:47:30.3168 [INFO]   Chat: Sigma Draconis (to ID:0): Server: Use !wiki in chat to open our Wiki in the Steam Browser Overlay!
11:47:35.0298 [INFO]   Chat: Theta Draconis (to ID:0): malus_71live: /
11:47:47.5172 [INFO]   ServerGatePlugin.BoundrySystem.BoundaryThread: Retry #100 Attack core
11:48:00.4849 [INFO]   Chat: Sigma Draconis (to ID:0): Server: Automated cleanup commencing shortly.  Please ensure your ships and stations follow the guidance on the Draconis wiki.
11:48:04.9198 [ERROR]  Torch: Frozen thread dump Main thread
Common prefix:
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read5400_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read5403_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6307_Item()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ShipBlueprintDefinitionSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read4518_MyObjectBuilder_Definitions(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6213_Definitions()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_DefinitionsSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.DeserializeXML(Stream reader, MyObjectBuilder_Base& objectBuilder, Type builderType, Dictionary`2 typeOverrideMap)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.DeserializeXML[T](Stream reader, T& objectBuilder)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.DeserializeXML[T](String path, T& objectBuilder, UInt64& fileSize)
   at VRage.ObjectBuilders.MyObjectBuilderSerializer.DeserializeXML[T](String path, T& objectBuilder)
   at QuantumHangar.GridMethods.LoadGrid(String GridName, MyCharacter Player, Int64 TargetPlayerID, Boolean keepOriginalLocation, Chat chat, Hangar Plugin, Boolean force) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\Utils.cs:line 167
   at QuantumHangar.Utilities.HangarChecks.LoadGridFile(String GridName, PlayerInfo Data, GridStamp Grid, Boolean admin) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 2448
   at QuantumHangar.Utilities.HangarChecks.LoadGrid(String GridNameOrNumber, Boolean ForceLoadAtSavePosition) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\Utilities\HangarChecks.cs:line 270
   at QuantumHangar.ChatCommands.Load(String GridNameOrNumber, Boolean LoadAtSavePosition) in C:\Users\Garrett Fulghum\source\repos\QuantumHangar\ChatCommands.cs:line 51
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
   at Torch.Commands.CommandManager.<>c__DisplayClass21_1.<HandleCommand>b__1() in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\CommandManager.cs:line 159
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Suffix 0
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.InitIDs()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)

Suffix 1
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.InitIDs()

Suffix 2
   at System.MarvinHash.ComputeHash(Byte* data, Int32 count, UInt64 seed)
   at System.Xml.NameTable.Add(String key)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.InitIDs()
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read5731_ComponentData(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read5732_Item(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read5750_MyObjectBuilder_TextPanel(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6298_MyObjectBuilder_TextPanel()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_TextPanelSerializer.Deserialize(XmlSerializationReader reader)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VRage.MyXmlSerializerBase`1.Deserialize(XmlReader reader, XmlSerializer serializer, String customRootName)
   at VRage.MyAbstractXmlSerializer`1.ReadXml(XmlReader reader)
   at System.Xml.Serialization.XmlSerializationReader.ReadSerializable(IXmlSerializable serializable, Boolean wrappedAny)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1830_MyObjectBuilder_CubeGrid(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read1843_MyObjectBuilder_Projector(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReader1.Read6295_MyObjectBuilder_Projector()
   at Microsoft.Xml.Serialization.GeneratedAssembly.MyObjectBuilder_ProjectorSerializer.Deserialize(XmlSerializationReader reader)


11:48:04.9198 [FATAL]  Initializer: System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 287
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
System.TimeoutException: Server watchdog detected that the server was frozen for at least 60 seconds.
   at Torch.Server.TorchServer.CheckServerResponding(Object state) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 287
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
11:48:04.9198 [INFO]   Initializer: Generating minidump at C:\Torch-Servers\SEDS9\Instance\Minidump.dmp
11:48:04.9198 [ERROR]  Initializer: Keen broke the minidump, sorry.
11:48:10.1557 [INFO]   SteamCMD: Checking for DS updates.```

**Comment by BobDaRoss** [comment]
It looks like it wasnt a ship BP. However, it should no longer crash in this spot. It will just throw an error and continue.
